#   ########################################################################
#   Copyright 2021 Splunk Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#   ########################################################################
# action.yml
name: "Addon Factory UCC Framework package generator"
description: "Produce splunk package"
inputs:
  version:
    description: Version stamp for output
    required: true
outputs:
  OUTPUT:
    description: "Package produced from the build"
    value: ${{ steps.output.outputs.result }}
runs:
  using: "composite"
  steps:
    - run: |
        if [ ! -z $INPUT_VERSION ]; then ARG_VERSION="--ta-version=${INPUT_VERSION}"; fi
        echo "::set-output name=result::$(echo $ARG_VERSION)"
        echo running ucc-gen $ARG_VERSION
        ucc-gen $ARG_VERSION
      shell: bash
      env:
        INPUT_VERSION: ${{ inputs.version }}
    - run: chmod -R +r output
      shell: bash
    - id: output
      shell: bash
      run: |
        OUTPUT=output/$(ls output/)
        SOURCE_REGEX='^.*/$'
        if [[ $OUTPUT =~ $SOURCE_REGEX ]];
        then
            echo Removing trailing / from OUTPUT slim is picky
            OUTPUT=$(echo $OUTPUT | sed 's/\(.*\)\//\1/')
        fi
        echo "::set-output name=result::$(echo $OUTPUT)"
